### ISSUE TITLE
Implementing color switching for sensorbox object.

### ISSUE THREAD

**Issue by molztim** [AG-Schumann/doberview2#61]
For alarming, monitoring, etc., a way to change the background color of sensorboxes would be a nice feature. This just needs to combine the features of valves and sensorboxes together: Show value and set background color according to a class in the svg file.

**Comment by adambrown1** [comment]
I think the same outcome is already possible. Just set the sensor box to have a transparent background and put the valve box behind it with colour change.

The only possible problem is what happens if you want to click on the valve, but it isn't clear what should happen anyway.

@molztim If I misunderstood and this is actually about implementing the logic for checking whether a sensor is outside its alarm range and changing the colouzr based on that feel free to reopen (maybe with a new title)
